<?php
  //echo '<pre>';print_r(Mage::registry('current_product'));exit;	
  $webPath = $this->getWebPath();
?>
<div class="wrapper">
          <div class="page">
                <div class="main-container col1-layout">
            <div class="main">
                                <div class="col-main container">
                    <div class="row2">
                        <div class="col-sm-12">
                                                        
    
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="<?php echo $webpath; ?>../js/designer/assets/css/tool-css.css" media="screen">
<link rel="stylesheet" type="text/css" href="<?php echo $webpath; ?>../js/designer/assets/css/add-name.css" media="screen">
<link rel="stylesheet" type="text/css" href="<?php echo $webpath; ?>../js/designer/assets/css/add-art.css" media="screen"/>
<link rel="stylesheet" type="text/css" href="<?php echo $webpath; ?>../js/designer/assets/css/print-proof.css" media="screen"/>
<link rel="stylesheet" type="text/css" href="<?php echo $webpath; ?>../js/designer/assets/css/responsive.css" media="screen"/>
<link rel="stylesheet" type="text/css" href="<?php echo $webpath; ?>../js/designer/assets/css/colorpicker.css" media="screen"/>
<script>
    var site_Url = '<?php echo $webpath; ?>js/designer/';
	var get_Help_url = '<?php echo $webpath; ?>../design/';
	var sleev_Print_url = '<?php echo $webpath; ?>../print_locations_sleeve/';
	var product_Id = '';
	var dataAccess_Url = '<?php echo $webpath; ?>';
	var login_Type = 'user';
	var hoodie_Flag = '';
	var blanket_designer = '';
	var edit_Flag = '';
	var can_print = '';
	var design_Id = '';
	var dir_Path = '<?php echo Mage::getBaseDir(); ?>';
	var imageHttpPath = '<?php echo $webpath; ?>';
	var sleeve_Print='';
	var contactUs='<?php echo $webpath; ?>contacts';
</script>
<script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/libraryjs/colorpicker.js"></script>
<script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/libraryjs/angular.js"></script>
<script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/models/model.js"></script>
<script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/libraryjs/undo-redo.js"></script>




<div class="designer-tool" ng-app="CustomInkApp">


    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/appcontroller.js"></script>

    <header>
        <div class="row">
            <div class="col-sm-4">
                <a target="_self" href="<?php echo $webpath; ?>"><img alt="" src="<?php echo $webpath; ?>skin/frontend/rwd/airborne/images/logo.png"> </a>
            </div>

            <div class="col-sm-4">
                <ul class="design-links">
                    <li>
                        <a target="_self" href="<?php echo $webpath; ?>products.html">Products </a>
                    </li>
                    <!--<li>
                            <a href="<?php echo $webpath; ?>hoodie-builder.html">hoodie builder</a>
                    </li>-->

                    <li>
                        <a target="_self" href="<?php echo $webpath; ?>inspiration.html">design ideas</a>
                    </li>

                    <li>
                        <a target="_self" href="<?php echo $webpath; ?>your-account.html">about us</a>
                    </li>
                </ul>
            </div>











            <div class="col-sm-4">
                <ul class="chat-section">
                    <li>
                        <span>talk to a real person</span>
                        <a href="tel:8002934232">800-293-4232</a>
                    </li>

                    <li>
                        <span>chat with a real person </span>
                        <a href="#">live chat now</a>
                    </li>
                </ul>
            </div>
        </div><!--row-->
    </header>


    <div class="tool-wrap" ng-controller="ManageViewController">
        <div class="distress-box"><label class="distress"><input class="distres-effect" type="checkbox" /> <span>Select Distress</span></label>
            <!--  <div class="direction-rotation clearfix">
            <a href="javascript:void(0)"><i class="undo"></i>
            <span>Undo</span>
            </a>
            <a href="javascript:void(0)"><i class="redo"></i>
            <span>Redo</span>
            </a>
            </div>  -->
        </div>
        <div class="overlay-wrapper">

        </div>
        <div class="preloader-overlay-wrapper">

        </div>
        <div class="preloaderHolder">
            <div class="preloaderDiv">

                <span class="preloaderHeading">Prepare To Create!</span>	
                <span class="preloaderSubHeading">Initializing...</span>
                <img src="<?php echo $webpath; ?>js/designer/assets/images/preloader.GIF"></img>
            </div>
        </div>
        <div class="getPricePopUp">
            <ul>
                <li><img class="closeNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/PopupCross.png"></img></li>
                <li><span class="top-header">Get Your Price </span></li>
                <li><span class="colorInfo">Enter quantity for your exact, All-Inclusive Price. </span></li>
                <li>
                    <div class="getSizeHolderParent">

                        <div class="getSizeHolder">
                            <div class="leftGetPrice">
                                <img id="frontPreviewThumb" class="canvasPreview">
                                </img>
                                <img id="frontCanvasThumb" class="canvasPreview">
                                </img>
                            </div>	
                            <div class="rightGetPrice">
                                <div>
                                    <span ng-bind="productName" class="addNameSizeBigHeading"></>
                                </div>
                                <div>
                                    <span ng-bind="productColor" class="addNameSizeBigHeading">Color: Gold </>
                                </div>
                                <div>
                                    <div class="item-sizes-container">
                                        <div class="item-size" ng-repeat="sizes in productSizeData">
                                            <div class="sizeAlign">{{sizes.sizeGroupTitle}}</div>
                                            <div class="item-size-values">
                                                <div class="item-size-label-and-input" ng-repeat="size in sizes.sizes">
                                                    <label>{{size.title}}</label>
                                                    <div><input type="text" sizeValue="{{size.title}}"></div></div>
                                            </div>
                                        </div>	
                                    </div>
                                </div>				
                            </div>
                        </div>
                        <div class="viewSizeLineUp">
                            <img src="<?php echo $webpath; ?>js/designer/assets/images/size.png"></img>
                            <a rel="popup" data-popup-options="width=700,height=800,scrollbars=yes,toolbar=yes,menubar=no,location=yes,resizable=yes" href="javascript:void(0)" class="viewSizing italicText"><span>View Sizing Line-up</span><span class="upperWord">SM</span></a>	
                        </div>
                    </div>
                </li>
                <li ng-show="qtyWarning">
                    <div  class="sizeAndDeliveryWarning">
                        <img src="<?php echo $webpath; ?>js/designer/assets/images/warning.png"></img>
                        <div>No quantities entered</div>
                        <span class="addNameSmallHeading">Please enter quantities to get a quote. </span>
                    </div>	
                </li>
                <li ><span class="addNameSizeBigHeading">Enter your delivery ZIP Code for your Guaranteed Delivery Date.</span> </li>
                <li><input class="zipCode" placeholder="Delivery Zip Code"></input><a class="addNameSizeBigHeading" href="javascript:void(0)"> Outside the U.S. or Canada?</a></li>
                <li ng-show="zipWarning">
                    <div class="sizeAndDeliveryWarning">
                        <img src="<?php echo $webpath; ?>js/designer/assets/images/warning.png"></img>
                        <div>Please enter your ZIP Code to get an All-Inclusive Price and a Guaranteed Delivery Date. </div>

                    </div>	
                </li>
                <li  ng-show="minQtyWarning">
                    <div class="minQtyWarning sizeAndDeliveryWarning">
                        <img src="<?php echo $webpath; ?>js/designer/assets/images/warning.png"></img>
                        <div>One or more of your items has a minimum quantity of 6 </div>
                        <!-- <span class="addNameSmallHeading">Please increase your total quantity above to 6 or more, or <a href="javascript:void(0)">choose another color</a> available at any quantity. </span> -->

                    </div>	
                </li>
                <li class="getPriceLi">
                    <a id="getPriceContinue" class="addText" href="javascript:void(0)">Continue</a>
                    <span class="shiftOr addNameSizeBigHeading">Or</span>
                    <a id="getPriceCancel" class="addNameSizeBigHeading" href="javascript:void(0)">Cancel</a>
                </li>
            </ul>
            <!-- <span ng-show="error1Flag" class="errorLabel">Your design name is blank or invalid. Design names are limited to 10 characters and cannot contain spaces or special symbols (?, -, #, etc.).</span>	
            <span ng-show="error2Flag" class="errorLabel2">Your email address is blank or invalid. The address should be in a format similar to 'user@example.com'.</span>	 -->
        </div>
        <div class="getPricePopUp2">
            <div class="leftGetPrice2">
                <ul>
                    <li>
                        <div class="previewHolder">
                            <div class="frontPreview">
                                <div class="frontPreviewBox">
                                    <img id="frontPreviewImg" class="canImage"></img>
                                    <img id="frontCanImage" class="canImage"></img>
                                </div>	
                            </div>
                            <div class="backPreview">
                                <div class="backPreviewBox">
                                    <img id="backPreviewImg" class="canImage"></img>
                                    <img id="backCanImage" class="canImage"></img>
                                </div>	
                            </div>		
                        </div>	
                    </li>
                    <li>
                        <div class="getPriceQtyInfo">
                            <span ng-show="nonEmptySection" class="singlePrice" ng-bind="discountPrice"></span>
                            <span class="addNameSizeBigHeading" ng-bind="productName"></span>
                            <span class="addNameSizeBigHeading" ng-bind="productColor"></span>
                            <span class="addNameSizeBigHeading" ng-bind="productQtyLabel"></span>
                        </div>		
                    </li>
                    <li class="getPriceChangeQty"><span class="addNameSizeBigHeading">Total Quantity:{{totalQty}}</span><a href="javascript:void(0)" class="addText openSizePopup">Change</a></li>
                    <li ng-show="nonEmptySection" class="seeMorePricingLi">
                        <div class="seeMorePricingInfo">
                            <div class="addNameSizeBigHeading">Watch your price drop!</div>
                            <div class="addNameSmallHeading2">The more you order, the more you save.
                                Order 10 and pay $13.24 each, or 20 and pay $8.80 each. 
                            </div>
                            <div><a>See More Money Saving Tips </a></div>
                        </div>
                    </li>
                </ul>	
            </div>
            <div class="rightGetPrice2">
                <img class="closeNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/PopupCross.png"></img></li>
                <div ng-show="emptySection" class="empty-design-section">
                    <img src="<?php echo $webpath; ?>js/designer/assets/images/warning.png">
                    </img>
                    <div class="instruct-section">
                        <div>
                            Your design is blank! 
                        </div>
                        <div>
                            Where do you go from here?  
                        </div>
                        <div>
                            1.Get a <a href="javascript:void(0)">quote on blank items.</a>   
                        </div>
                        <div>
                            2.<a class="showText" href="javascript:void(0)">Add text</a> or <a class="showArt" href="javascript:void(0)">art</a> first to get an accurate price 
                        </div>
                        <div>
                            3.You’re not ready to design yet, but want a quote? <a href="javascript:void(0)">Use the Quick Quote tool.</a>  
                        </div>
                    </div>				
                </div>
                <div ng-show="nonEmptySection" class="priceSection">
                    <div class="sectionElement">
                        <span class="top-header">YOUR ALL-INCLUSIVE PRICE </span>
                    </div>
                    <div class="sectionElement" ng-show="disscountEnable">
                        <span class="discount-sumary disabled" ng-bind="totalPriceWithOutDisscount"> </span>
                        <div class="pecentage"> {{discountPercentage}} Savings with Volume Discount! </div>
                    </div>
                    <div class="sectionElement totalPriceSection">
                        {{totalPrice}}<span>Total</span>

                    </div>
                    <div class="sectionElement avg-summary">
                        <span class="qw-bold">{{totalQty}}</span>
                        Pieces at
                        <span class="qw-bold">{{discountPriceOnly}}</span>
                        each 
                    </div>
                    <div class="sectionElement">
                        <img src="<?php echo $webpath; ?>js/designer/assets/images/shipping_box.png" > </img>
                        <div class="shipping_box" > FREE, GUARANTEED 2-WEEK DELIVERY BY 
                            <span ng-bind="deliveryDate"></span>
                        </div>
                    </div>	
                    <div class="sectionElement">
                        <div class="shippingAddress">{{shippingAddress}}<a href="javascript:void(0)" class="addText openSizePopup">Change</a></div>
                    </div>
                    <div class="sectionElement">
                        <div class="shippingDate">
                            Get it <span class="qw-bold" ng-bind="fastDeliveryTime"></span> with 1-Week Rush - Add 10%
                            Need it before the {{fastDevDate}}? 
                            <a href="javascript:void(0)">Call and ask for Super Rush</a></div>
                    </div>
                    <div class="sectionElement buy-now-section-header">
                        <div class="buy-now-section">
                            <a href="javascript:void(0)" class="buy-now">Buy Now</a>
                            <a class="save-Continue" href="javascript:void(0)">Save &amp; Continue Designing</a>
                        </div>
                    </div>		
                </div>	
            </div>
        </div>	
        <div class="upload1PopUp">
            <ul>
                <li>
                    <span class="addNameSmallHeading2">Upload Your Art
                    </span>
                    <img class="closeNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/PopupCross.png">
                    </img>
                    <div class="horizontalRule"></div>
                </li>
                <li><span class="top-header">Upload Your Art</span></li>
                <li><span class="addNameSizeBigHeading">Choose a file from your computer.</span></li>
                <li>
                    <div class="upload-panel">
                        <form id="UploadForm" name="uploadform" action="<?php echo $webpath; ?>js/designer/php/processupload.php" method="post" enctype="multipart/form-data">

                            <div class="customfile-container">
                                <input type="file" id="file" name="ImageFile" multiple />
                            </div>
                            <span class="addNameSmallHeading2">We accept all common image file types. <a class="seeUploadDetail" href="javascript:void(0)">See details.</a></span>


                            <div class="upload-cancel-upload"><a href="javascript:void(0)" class="uploadCancel addText">Cancel</a> <input type="submit" value="Upload" class="addText" ></div>		

                        </form>
                        <span ng-show="uploadErrorFlag" class="errorLabel">Whoops! Please select a file to upload</span>
                    </div>
                </li>
                <li ng-show="seeDetailFlag">
                    <div  class="accept-file-types">
                        <h4>Accepted File Types <span>(Max file size: 10MB)</span></h4>
                        <ul class="clearfix">
                            <li>JPEG Image .jpg, .jpeg</li>
                            <li>Adobe Acrobat .pdf</li>
                            <li>PNG Image .png</li>
                            <li>GIF Image .gif</li>
                        </ul>
                    </div>
                </li>

            </ul>	
        </div>
        <div class="artResizeErrorPopUp">
            <ul>
                <li>
                    <span class="top-header">An Error has occuered
                    </span>
                    <img class="closeNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/warning.png">
                    </img>
                    <div class="horizontalRule"></div>
                </li>

            </ul>
            <div class="artErrorSection">
                <span ng-show="errorWidth" class="addNameSizeBigHeading">Please enter a valid numerical width value.</span>
                <span ng-show="!errorWidth" class="addNameSizeBigHeading">Please enter a valid numerical height value.</span>
            </div>
            <a class="addText" href="javascript:void(0)">OK</a>
        </div>
        <div class="save-category-popup">
            <ul>
                <li>
                    <span class="top-header">Select Category/Sub Category
                    </span>
                    <img class="closeNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/PopupCross.png">
                    </img>
                    <div class="horizontalRule"></div>
                </li>
                <li><input class="design-name-txt" type="text" placeholder="Enter Design Name"></input></li>
                <li>
                    <div class="item-size-values">
                        <div class="item-size-label-and-input" ng-repeat="category in selectCat">
                            <label>{{category.name}}</label>
                            <div ng-repeat="subcat in category.subCategory"><input cat-binding type="checkbox" ng-model="trueFalseFlag"></input><span>{{subcat.name}}</span></div>
                        </div>
                    </div>	
                </li>
                <li><a class="addText" href="javascript:void(0)">Save/Send</a></li>	

            </ul>

        </div>		
        <div class="upload2PopUp">
            <ul class="upper-ul">
                <li>
                    <span ng-show="uploadShow" class="back-browse-popup addNameSmallHeading2">Go Back
                    </span>
                    <img class="closeNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/PopupCross.png">
                    </img>
                    <div class="horizontalRule"></div>
                </li>
                <li ng-show="!uploadShow"><img src="<?php echo $webpath; ?>js/designer/assets/images/upload_progress.jpg"></img></li>
                <li ng-show="!uploadShow"><span class="addNameSizeBigHeading">Free Professional Art Review for Every Order</span></li>
                <li ng-show="!uploadShow"><div class="progress-bar-holder">
                        <div class="progress-bar-percentage">

                        </div>
                    </div>
                </li>
                <li ng-show="!uploadShow"><span class="addNameSmallHeading2">Upload in Progress
                    </span>
                </li>
                <li ng-show="uploadShow">
                    <div class="upload-image-section">
                        <div class="left-image-color-holder">
                            <span class="top-header">Which colors should we use to print your image?</span>
                            <span class="addNameSizeBigHeading">Our color recommendations have been pre-selected to help you get started.</span>
                            <span class="addNameSmallHeading2">{{uploadColorLabel}}</span>
                            <ul class="uploadColorUl">
                                <li ng-repeat="color in uploadArtColors.colors">
                                    <div pid="{{color.colorId}}" cprice="{{color.price}}" ctitle="{{color.title}}"  pcolor="{{color.code}}" ng-style="{'background-color':'#{{color.code}}'}">
                                        <img upload-Binding ng-show="colorSelected"   class="slectedColor"></img>
                                    </div>
                                </li>
                            </ul>
                            <div ng-show="uploadSelectColorFlag" class="sizeAndDeliveryWarning">
                                <img ng-attr-src="{{imageUrl}}assets/images/warning.png"></img>
                                <div>Please select at least one color. </div>


                            </div>	
                            <a id="addUploadedImage" href="javascript:void(0)" class="addText">Confirm Colors</a>
                        </div>
                        <div class="right-image-holder">
                            <canvas id="uploadDesignCan" width="348" height="383" style="border:1px none blue;"></canvas>
                        </div>	
                    </div>	
                </li>	


            </ul>	
        </div>		
        <div class="saveYourDesignPopUp">
            <ul>
                <li>
                    <span class="saveDesignAndNameNumberTitle addNameSmallHeading2">Save Design/Send it to Friends
                    </span>
                    <img class="closeNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/PopupCross.png">
                    </img>
                    <div class="horizontalRule"></div>
                </li>
                <li><span class="top-header">Save Your Design</span></li>
                <li class="save-table-info"><span class="addNameSizeBigHeading">Your updated list will be saved when you save your design.</span></li>
                <li ng-show="designcheck">
                    <div class="designNameCheck">
                        <span class="addNameSizeBigHeading">You have a saved design named '{{saveDesignName}}'. Do you want to replace it or enter a new name for this design?</span>
                        <div ><input id="reRadio"  class="selectRadio" type="radio" name="radio1" checked></input>  Replace '{{saveDesignName}}' with this design
                        </div>	
                        <div><input id="newRadio"  class="selectRadio" type="radio" name="radio1"></input>  Enter a new name for this design
                        </div>
                        <div>
                            <input id="saveNowSendMail" class="selectCheck"  type="checkbox" checked></input>  Send me an email with my updated design
                        </div>	
                    </div>
                </li>
                <li ng-show="nonDesigncheck"><span id="saveSubHead" class="colorInfo">Save your design to use later, then share it with friends via email, Facebook, or Twitter.</span></li>
                <li ng-show="nonDesigncheck"><span class="addNameSizeBigHeading">Name Your Design:</span></li>
                <li ng-show="nonDesigncheck"><input class="saveDesignName" type="text"></input></li>
                <li ng-show="nonDesigncheck"><span class="saveMaxCharecter">10 character max:</span></li>
                <li ng-show="nonDesigncheck"><span class="addNameSizeBigHeading">Your Email Address:</span></li>
                <li ng-show="nonDesigncheck"><input class="saveUserId" type="text"></input></li>

                <li ng-show="nonDesigncheck"><span class="addNameSizeBigHeading">Your email address is safe with us. Read our <a class="saveBoldTitle" href="javascript:void(0)">Privacy Policy.</a></span></li>
                <li class="saveDesignLi"><a id="saveDesignToAccount" class="addText" href="javascript:void(0)">Save Design</a><span class="addNameSizeBigHeading">Or</span><a href="javascript:void(0)" class="closeSavePopup saveBoldTitle">Cancel</a></li> 
            </ul>
            <span ng-show="error1Flag" class="errorLabel">Your design name is blank or invalid. Design names are limited to 10 characters and cannot contain spaces or special symbols (?, -, #, etc.).</span>	
            <span ng-show="error2Flag" class="errorLabel2">Your email address is blank or invalid. The address should be in a format similar to 'user@example.com'.</span>	
        </div>
        <div class="print-proof-popup" style="width: 750px;position: fixed;height:620px;z-index: 1010;left:0px;top:0px;display:none;border:1px none red;background: #fff;overflow:auto;font-family: 'Oswald', sans-serif;	">
            <div class="print-proof-page" style="font-size: 11px;  font-weight: lighter;  padding-bottom: 1px;">
                <div id="printBtnContainer" style="border-bottom: 1px solid #eaeaea;  font-size:10px;  margin: 0 0 20px; position: relative;  overflow: hidden; padding: 5px;">
                    <button id="printBtn" style="height: 30px; line-height: 30px;border-radius:4px;"  class="button">Print Proof...</button>
                    Your print proof is ready!
                    <img class="closePrint" style="cursor: pointer; right: 8px; position: absolute; top: 10px;" src="<?php echo $webpath; ?>js/designer/assets/images/PopupCross.png">
                    </img>
                </div>
                <div class="print-content" style="width:96%; margin:0 auto;">
                    <header class="hd" style="border-bottom: 1px solid #666;">
                        <section id="logo" style="padding: 15px 0;">
                            <div class="header-wrapper">
                                <ul style="margin:0 auto;list-style: none !important;padding: 0px;">
                                    <li class="logo-main">
                                        <img alt="Header-logo"  src="<?php echo $webpath; ?>skin/frontend/rwd/airborne/images/logo.png"  />
                                    </li>

                                </ul>
                            </div>
                        </section>
                    </header>
                    <div class="designView" style="text-align:center;">
                        <h2 style="line-height: 24px;color:#000;font-family: TitilliumWeb Bold,serif;font-size: 12px">PRINTED PROOF</h2>
                        <ul style="list-style: none !important;padding: 0px;display:block; float: left; margin-right:10px; clear:both;">
                            <li style="width:180px;float:left;margin-right: 10px"><div class="frontPreview" style="position: relative;width: 182px;height: 164px;margin-left: 3px;background-color: #dcd9d4;border: 1px none red;">
                                    <div class="frontPreviewBox">
                                        <img width="180" height="161" style="height: 161px;left: 0;position: absolute;top: 0;width: 180px;" id="printFrontImg"  class="canImage"></img>
                                        <img  width="180" height="161" style="height: 161px;left: 0;position: absolute;top: 0;width: 180px;" id="frontPrintImage" class="canImage"></img>
                                    </div>	
                                </div>
                            </li>
                            <li style="width:180px;float:left;margin-right: 10px"><div class="backPreview" style="position: relative;width: 182px;height: 164px;margin-left: 3px;background-color: #dcd9d4;border: 1px none red;">
                                    <div class="backPreviewBox">
                                        <img width="180" height="161" style="height: 161px;left: 0;position: absolute;top: 0;width: 180px;" id="printBackImg"  class="canImage"></img>
                                        <img width="180" height="161" style="height: 161px;left: 0;position: absolute;top: 0;width: 180px;" id="backPrintImage" class="canImage"></img>
                                    </div>	
                                </div>	
                            </li>
                        </ul>
                    </div>
                    <div class="productDescription" style="margin: 10px auto;">
                        <p style="padding-bottom: 1px;">
                            <span style="padding-right: 5px;font-weight:bold;" class="title">Decoration:</span>depends on quantity  </p>
                        <p>
                            <span style="padding-right: 5px;font-weight:bold;" class="title">All-Inclusive Price:</span> depends on quantities
                        </p>
                        <p>
                            <span style="padding-right: 5px;font-weight:bold;" class="title">Delivery Time:</span> Free 2-week delivery. (For 1-week rush, add $9.95.)
                        </p>
                    </div>
                    <div class="itemInfo" style="margin: 10px auto; width:68%; float:left;">
                        <p>
                            <span style="float:left;margin-right:4px;" class="title">Item:</span> {{productName}}
                        </p>
                        <div>
                            <span style="float:left;margin-right:4px;" class="title">Quantity:</span>
                        </div>
                        <div style="height: 66px;width: 100%;">


                            <div>
                                <div class="print-sizes-container">
                                    <div  style="float: left;margin-left:10px;font-size: 12px;color: #000000;font-family: "Open Sans","Sans serif";" ng-repeat="sizes in productSizeData">
                                          <div class="sizeAlign">{{sizes.sizeGroupTitle}}</div>
                                        <div class="print-item-size"  style="width: auto;margin-right: 3px;float: left;text-align:center;">
                                            <div  style="width: auto;margin-right: 3px;float: left;text-align:center;" ng-repeat="size in sizes.sizes">
                                                <label>{{size.title}}</label>
                                                <div><input  style="width: 27px;height: 20px;padding: 0px;border: 1px solid;pointer-events:none;" type="text" sizeValue="{{size.title}}">

                                                </div>
                                            </div>
                                        </div>
                                    </div>	
                                </div>
                            </div>				
                        </div>
                        <div>
                            <span style="float: right; padding-right: 12px;">Total Quantity: {{totalQty}}</span>
                        </div>
                    </div>
                    <div class="orderBlock" style="float:left;width:100%">
                        <section style="padding-top: 0;">
                            <h2 style="font-size: 16px;color: #000000">Call Us to Place your Order</h2>
                            <p>
                                Have a friendly Flip Shop representative help you place your order! Call us at <strong>800-293-4232.</strong>
                                <br>
                                Talk to a Real Person 8am-11pm ET Mon-Fri, 10am-6pm ET Saturday and 10am-9pm ET Sunday
                            </p>
                        </section>
                        <section>
                            <h2 style="font-size: 16px;color: #000000">Order or Revise Your Design Online</h2>
                            <p>
                                Retrieve your design at <strong>www.Flip Shop.com/accounts</strong> by using this number:
                                <strong>ccv0-0015-baxv</strong>.<br />
                                Use &quot;Checkout Now&quot; to pay by credit/debit card, check, or PO (for qualified institutions).
                            </p>
                        </section>
                        <section>
                            <h2 style="font-size: 16px;color: #000000">Mail Us Your Order Form</h2>
                            <p>
                                Please enter your contact information and mail this entire Printed Proof with a check - we will use the information below to confirm your payment and provide updates about your order.
                            </p>
                            <div class="contact-wrapper" style="width:40%">
                                <div class="order-form" >
                                    <form class="order" action="#">
                                        <div class="order-field">
                                            <label>Name:</label> <div><input class="print-name-value" value=""/></div>
                                        </div>

                                        <div class="order-field">
                                            <label>Email:</label> <div><input class="print-email-value" value=""/></div>
                                        </div>
                                        <div class="order-field">
                                            <label>Phone:</label> <div><input class="print-phone-value" value=""/></div>
                                        </div>
                                    </form>
                                </div>
                                <div class="mailTo" style="width:200px;">
                                    Mail this form with a check to:
                                    <br />
                                    Flip Shop, Attn: Accounts Receivable<br />
                                    PO Box 791253<br />
                                    Baltimore, MD 21279
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>	
        <div class="buyNowPopUp">
            <ul>
                <li>
                    <span class="addNameSmallHeading2">Buy Now
                    </span>
                    <img class="closeNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/PopupCross.png">
                    </img>
                    <div class="horizontalRule"></div>
                </li>
                <li><span class="top-header">Buy Now</span></li>
                <li ng-show="!designcheck" ><span class="colorInfo">We'll save your final design when you Continue to Shipping.</span></li>

                <li ng-show="designcheck">
                    <div class="designNameCheck">
                        <span class="addNameSizeBigHeading">Please save a final version of your design before you Continue to Shipping.</span>

                        <div ><input id="buyreRadio"  class="selectRadio" type="radio" name="radio2" checked></input> Save this as the final version of '{{saveDesignName}}' 
                        </div>	
                        <div><input id="buynewRadio"  class="selectRadio" type="radio" name="radio2"></input>  Enter a new name for this final design
                        </div>
                        <div>
                            <input id="buyNowSendMail" class="selectCheck"  type="checkbox" checked></input>  Send me an email with my updated design
                        </div>	
                    </div>
                </li>

                <li ng-show="nonDesigncheck" ><span class="addNameSizeBigHeading">Name Your Design:</span></li>

                <li ng-show="nonDesigncheck" ><input class="buyDesignName" type="text" maxlength="10"></input></li>
                <li ng-show="nonDesigncheck" ><span class="saveMaxCharecter">10 character max:</span></li>
                <li  ><span class="colorInfo">Please verify the email address where you want us to send information about your order.</span></li>
                <li  ><span class="addNameSizeBigHeading">Your Email Address:</span></li>
                <li  ><input class="buyUserId" type="text"></input></li>
                <li  ><span class="addNameSizeBigHeading">Verify Your Email Address:</span></li>
                <li  ><input class="buyUserIdConfirm" type="text"></input></li>

                <li  ><span class="addNameSizeBigHeading">Your email address is safe with us. Read our <a class="saveBoldTitle" href="javascript:void(0)">Privacy Policy.</a></span></li>
                <li class="saveDesignLi"><a  class="addText continue-shipping" href="javascript:void(0)">Continue to Shipping</a><span class="addNameSizeBigHeading">Or</span><a href="javascript:void(0)" class="closeBuyNowPopup saveBoldTitle">Return To Your Design</a></li> 
            </ul>
            <span ng-show="error1Flag" class="errorLabel">Your design name is blank or invalid. Design names are limited to 10 characters and cannot contain spaces or special symbols (?, -, #, etc.).</span>	
            <span ng-show="error2Flag" class="errorLabel2">Your email address is blank or invalid. The address should be in a format similar to 'user@example.com'.</span>
            <span ng-show="error3Flag" class="errorLabel3">Email addresses don't match.</span>		
        </div>
        <div class="swapItemPopup">
            <section>
                <span class="top-header">SWAP ITEM</span>
                <img class="close-btn"></img>
            </section>
            <section class="swapItemHolder">
                <div class="leftSwapItemPopup">
                    <span class="catHeading">All Categories:</span>
                    <div ng-repeat="item in items">
                        <a  href="javascript:void(0)" class="pCatId catHeading" pname="{{item.name}}" pcatid="{{item.catId}}" >{{item.name}}</a>
                        <br/>
                        <a  href="javascript:void(0)" ng-repeat="subcat in item.subCategory" class="pSubCatId subcatH" pname="{{subcat.name}}" pcatid="{{subcat.subCatId}}">{{subcat.name}},</a>
                    </div>	
                </div>
                <div class="rightSwapItemPopup" >
                    <a id="swapItemCategory" class="subcatH disabled" >{{pCatTitle}}</a>
                    <span ng-show="showMe" class="subcatH" >></span>
                    <a ng-show="showMe" class="subcatH disabled">{{pSubCatTitle}}</a>
                    <div ng-include="swaptempalate.url"></div>
                </div>	
            </section>	

        </div>
        <div class="enterNameNumberPopUp">
            <span class="top-header">No personalization type selected</span>
            <hr></hr>
            <img src="<?php echo $webpath; ?>js/designer/assets/images/warning.png"></img>
            <p>Please select one of the following options in order to begin entering your Names/Numbers list.
                If you are not ready to enter your list, please choose "No Personalization"</p>
            <ul>
                <li><a id="nameAndNumOnly" class="addText" href="javascript:void(0)">Names AND Numbers</a></li>
                <li><a id="nameOnly" class="addText" href="javascript:void(0)">Names only</a></li>
                <li><a id="numOnly" class="addText" href="javascript:void(0)">Numbers only</a></li>
                <li><a id="noPersonalizations" class="addText" href="javascript:void(0)">No Personalization</a></li>
            </ul>		
        </div>
        <div class="enterNameNumberSizePopUp">
            <ul>
                <li><span class="addNameSmallHeading2">Names And Numbers List</span><img class="closeNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/PopupCross.png"></img>
                    <div class="horizontalRule"></div>	
                </li>
                <li><span class="top-header">Names And Numbers List</span></li>
                <li><span class="addNameSizeBigHeading">Enter your full list of names and numbers for accurate pricing</span></li>
                <li class="tableRowSeparator">
                    <div class="tableHolder">
                        <table class="number-tb">
                            <tr id="rowDetele_0">
                                <th class="rowdeleteTh"></th>
                                <th class="name">Name</th>
                                <th>Number</th>
                                <th class="size">Size</th>
                            </tr>
                            <tr  ng-repeat="items in [0, 1, 2, 3, 4, 5]" namenumber-Row>
                                <td class="rowdeleteTr"><img class="rowdelete"></img></td>
                                <td><input type="text" class="textbox1" /></td>
                                <td><input type="number" min="1"  class="textbox2" /></td>
                                <td class="size">
                                    <select class="tableSizeHolder">
                                        <option ng-repeat="size in nameSizes" value="{{size.title}}">{{size.title}}</option>
                                    </select>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="hintHolder">
                        <ul><li><span class="top-header">Helpful Hints</span><li>
                            <li><span class="addNameSmallHeading2">1. Don't see the size you want? Switch to a <a  class="showSwapSection"  href="javascript:void(0)">color or product</a> that has your size available.</span></li>
                            <li><span class="addNameSmallHeading2">2. Not able to enter names or numbers? Return to the <a class="closeNameNumTable" href="javascript:void(0)">settings</a> to select these options. </span></li>
                        </ul>
                    </div>	
                </li>
                <li><img class="addNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/addnames.png"></img><span class="addNameSmallHeading2">Names And Numbers List</span></li>
                <li class="nameNumberLabelLi"><table class="nameNumberLabel">
                        <tr>
                            <td class="nameAndNumberLabel"><b>Totals</b>: 0 names and 0 numbers on 0 items</td>
                        </tr>
                        <tr>
                                <!-- <td class"nameAndNumberSizeLabel"><b>Sizes</b>: (0/5) YXS (0/1) YL (0/1) YXL</td> -->
                            <td class="totalNameAndNumber"><b>Sizes</b>:</td>
                        </tr>
                    </table>
                    <a id="saveNameNumberInArr" class="addText" href="javascript:void(0)"> Done </a>
                </li>

            </ul>	
        </div>
        <div class="saveYourDesignPopUp2">
            <ul>
                <li><span class="saveDesignAndNameNumberTitle addNameSmallHeading2">Save Design/Send it to Friends</span><img class="closeNameSizePopup" src="<?php echo $webpath; ?>js/designer/assets/images/PopupCross.png"></img>
                    <div class="horizontalRule"></div>
                </li>

                <li><span class="top-header">We've saved '{{saveDesignName}}' and emailed you a link to your design.</span></li>
                <li ng-show="wrongInfoF" class="wrong-info">
                    <div  class="sizeAndDeliveryWarning">
                        <img src="<?php echo $webpath; ?>js/designer/assets/images/warning.png"></img>
                        <div>Oops! Looks like we're missing some information.</div>
                        <span class="addNameSmallHeading">Please fill in a recipient below. </span>
                    </div>	
                </li>
                <li ng-show="currectInfoF" class="currect-info">
                    <div  class="sizeAndDeliveryWarning">
                        <img src="<?php echo $webpath; ?>js/designer/assets/images/selected.png"></img>

                        <span class="addNameSmallHeading">Your email has been sent! Share again or <a href="javascript:void(0)">Return to Your Design.</a> </span>
                    </div>	
                </li>		
                <li>
                    <div class="partitionDiv">
                        <div class="leftPart">
                            <ul>
                                <li><span class="addNameSizeBigHeading">Email this design to your friends</span></li>
                                <li><span class="addNameSizeBigHeading">To</span></li>
                                <li><input class="bunchOfEmils" type="text" placeholder="Enter emails separated by Commas"></input></li>
                                <li><span class="addNameSizeBigHeading">Your Name</span></li>
                                <li><input class="enterYourName" type="text" placeholder="Enter Your Name"></input></li>
                                <li><span class="addNameSizeBigHeading">Message</span></li>
                                <li><textarea class="saveTextArea" >I just created this design. Take a look!</textarea>
                                <li class="saveDesignLi2">
                                    <span class="addNameSizeBigHeading">Your email address is safe with us.
                                        Read our<a class="saveBoldTitle" href="javascript:void(0)">Privacy Policy. </a></span>
                                    <a id="sendEmailToFriend"  class="addText" href="javascript:void(0)">Send</a></li>  
                            </ul>	
                        </div>
                        <div class="midPart">
                        </div>
                        <div class="rightPart">
                            <ul>
                                <li><span class="addNameSizeBigHeading">Share and collect sizes</span></li>
                                <li><img src="<?php echo $webpath; ?>js/designer/assets/images/share_overlay.png"></img></li>
                                <li><span class="addNameSizeBigHeading">Not sure of everyone's sizes? Use email or Facebook to invite your group to choose their sizes for a perfect fit.</span></li>
                                <li><a class="addText">Get Started</a></li>
                        </div>		
                    </div>
                </li>
                <li><div class="horizontalRule"></div></li>
                <li>
                    <span class="addNameSizeBigHeading">More Ways to Share:</span>
                    <ul class="socialShare">
                        <li><a class="faceBook-icon"></a><span>Facebook</span></li>
                        <li><a class="twitter-icon"></a><span>Twitter</span></li>
                        <li><a class="pintrest-icon"></a><span>Pinterest</span></li>
                    </ul>	
                </li>
            </ul>	
        </div>		
        <section class="started-tool" ng-model="template">

            <ul class="nav nav-tabs" role="tablist">
                <li>
                    <a href="javascript:void(0)"   role="tab" data-toggle="tab"> <img alt="" src="<?php echo $webpath; ?>js/designer/assets/images/swap-item-icon.png" > <small>Swap item </small><i class="hover-arrow"> &nbsp;</i> </a>
                </li>
                <li>
                    <a href="javascript:void(0)"   role="tab" data-toggle="tab"> <img alt="" src="<?php echo $webpath; ?>js/designer/assets/images/add-text-icon.png" > <small>add text</small><i class="hover-arrow"> &nbsp;</i></a>
                </li>
                <li>
                    <a href="javascript:void(0)"   role="tab" data-toggle="tab"> <img alt="" src="<?php echo $webpath; ?>js/designer/assets/images/add-art-icon.png" > <small>add art</small><i class="hover-arrow"> &nbsp;</i></a>
                </li>
                <li>
                    <a class="banket-disabled" href="javascript:void(0)"   role="tab" data-toggle="tab"> <img alt="" src="<?php echo $webpath; ?>js/designer/assets/images/add-name-icon.png" > <small>add name</small><i class="hover-arrow"> &nbsp;</i></a>
                </li>

                <li>
                    <a href="javascript:void(0)"  role="tab" data-toggle="tab"> <img alt="" src="<?php echo $webpath; ?>js/designer/assets/images/add-note-icon.png" > <small>add note</small><i class="hover-arrow"> &nbsp;</i></a>
                </li>
            </ul>

            <!-- Tab panes -->

            <div class="tab-content" >
                <i class="close_tab visible-xs"></i>
                <div ng-include="template.url"></div>
            </div>
            <div class="viewWiseColorHolder quantity-holder">
                <div class="totalColorHolderPrice">
                    <span>Total Quantity: {{totalQty}}</span>
                    <span class="rightPos" >{{totalPrice}} total</span>
                </div>
                <div class="totalColorHolder">
                    <span>Printing:{{frontColorLenght}} Color Front, {{backColorLenght}} Color Back</span>
                    <a id="viewPriceSummary" class="rightPos">View price summary</a>
                </div>	
            </div>	
        </section><!--started-tool-->
        <section class="tool-product">
            <nav class="tool-links">
                <ul>
                    <li class="active">
                        <a id="switchProduct" href="javascript:void(0)"><i class="rotate-icon">&nbsp;</i> <span>rotate</span></a>
                    </li>

                    <li>
                        <a id="sleevePrint" href="javascript:void(0)" rel="popup" data-popup-options="width=700,height=800,scrollbars=yes,toolbar=yes,menubar=no,location=yes,resizable=yes"> <i class="print-icon">&nbsp;</i> <span>sleeve print</span></a>
                    </li>

                    <li>
                        <a id="zoomInOut" href="javascript:void(0)"><i class="zoom-icon">&nbsp;</i><span>zoom in</span></a>
                    </li>
                    <li>
                        <a id="printThis" href="javascript:void(0)" rel="popup" data-popup-options="width=700,height=800,scrollbars=yes,toolbar=yes,menubar=no,location=yes,resizable=yes"><i class="print-this-icon">&nbsp;</i><span>print this</span></a>
                    </li>
                    <li>
                        <a id="get_help" href="javascript:void(0)" rel="popup" data-popup-options="width=700,height=800,scrollbars=yes,toolbar=yes,menubar=no,location=yes,resizable=yes"> <i class="help">&nbsp;</i> <span>get help</span></a>
                    </li>
                </ul>
            </nav>

            <figure class="product-img">
                <div class="canvas-holder">
                    <div class="inner-canvas-holder">
                        <div class="inner-canvas-holder-zoom">
                                <!-- <img ng-show="frontSelected" class="frontImage"></img>
                                <img ng-show="backSelected" class="backImage"></img> -->
                            <div ng-show="frontSelected" class="frontImage">
                                <canvas id="frontCan" width="546" height="493" style="border:1px none black;position: absolute;left: 0px"></canvas>
                            </div>
                            <div ng-show="backSelected" class="backImage">
                                <canvas id="backCan" width="546" height="493" style="border:1px none black;position: absolute;left: 0px"></canvas>	
                            </div>	
                            <canvas id="designCan" width="546" height="493" style="border:1px none black;position: absolute;left: 0px"></canvas>
                            <div>

                            </div>
                        </div>
                        <label id="addObjectLoader" ng-show="addObjectLoaderVariable">Working..</label>
                        </figure>

                        <ul class="but-links">
                            <li>
                                <a href="javascript:void(0)" class="getPriceOpenPopUp"> <i class="price">&nbsp;</i> get price</a>
                            </li>

                            <li>
                                <a href="javascript:void(0)" class="openSavePopUp"> <i class="save">&nbsp;</i> save / send</a>
                            </li>

                            <li class="active">
                                <a href="javascript:void(0)" class="buy-product"> <i class="buy">&nbsp;</i> buy now</a>
                            </li>
                        </ul>
                        <div class="rightClickPopup">
                            <ul class="x-menu-list">
                                <li class="x-menu-list-item x-menu-item-active number-menu">
                                    <a id="enter_names_num" class="x-menu-item" href="#" unselectable="on" hidefocus="true">
                                        <img  class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/table_edit.png">
                                        <span  class="x-menu-item-text">Edit Names List</span>
                                    </a>
                                </li>
                                <li class="x-menu-list-item x-menu-item-active name-clip-menu">
                                    <a id="delete-object" class="x-menu-item" href="#" unselectable="on" hidefocus="true">
                                        <img  class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/style_delete.png">
                                        <span  class="x-menu-item-text">Delete</span>
                                    </a>
                                </li>
                                <li class="x-menu-list-item">
                                    <a id="center-object" class="x-menu-item" href="#" unselectable="on" hidefocus="true">
                                        <img id="ext-gen10" class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/shape_align_center.png">
                                        <span id="ext-gen11" class="x-menu-item-text">Center</span>
                                    </a>
                                </li>
                                <li id="x-menu-el-ext-comp-1003" class="x-menu-list-item x-menu-sep-li name-clip-menu">
                                    <span id="ext-gen14" class="x-menu-sep">&nbsp;</span>
                                </li>
                                <li class="x-menu-list-item name-clip-menu">
                                    <a id="copy-object" class="x-menu-item" href="#" unselectable="on" hidefocus="true">
                                        <img id="ext-gen10" class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/page_copy.png">
                                        <span id="ext-gen11" class="x-menu-item-text">Copy</span>
                                    </a>
                                </li>
                                <li class="x-menu-list-item name-clip-menu">
                                    <a id="cut-object" class="x-menu-item" href="#" unselectable="on" hidefocus="true">
                                        <img id="ext-gen10" class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/cut_red.png">
                                        <span id="ext-gen11" class="x-menu-item-text">Cut</span>
                                    </a>
                                </li>
                                <li class="x-menu-list-item name-clip-menu ">
                                    <a id="paste-object2" class="x-menu-item disabled" href="#" unselectable="on" hidefocus="true">
                                        <img id="ext-gen10" class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/paste_plain.png">
                                        <span id="ext-gen11" class="x-menu-item-text">Paste</span>
                                    </a>
                                </li>
                                <li id="x-menu-el-ext-comp-1003" class="x-menu-list-item x-menu-sep-li">
                                    <span id="ext-gen14" class="x-menu-sep">&nbsp;</span>
                                </li>
                                <li id="arrangeIcon" class="x-menu-list-item">
                                    <a id="ext-comp-1008" class="x-menu-item x-menu-item-arrow" href="#" unselectable="on" hidefocus="true">
                                        <img id="ext-gen22" class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/c.gif">
                                        <span id="ext-gen23" class="x-menu-item-text">Arrange</span>
                                    </a>
                                </li>
                            </ul>	
                        </div>

                        <div class="arrangeClickPopup">
                            <ul class="x-menu-list">
                                <li class="x-menu-list-item x-menu-item-active">
                                    <a id="bringback-object" class="x-menu-item" href="#" unselectable="on" hidefocus="true">
                                        <img id="ext-gen10" class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/shape_move_back.png">
                                        <span id="ext-gen11" class="x-menu-item-text">Send to Back</span>
                                    </a>
                                </li>
                                <li class="x-menu-list-item x-menu-item-active">
                                    <a id="backward-object" class="x-menu-item" href="#" unselectable="on" hidefocus="true">
                                        <img id="ext-gen10" class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/shape_move_backwards.png">
                                        <span id="ext-gen11" class="x-menu-item-text">Send Backward</span>
                                    </a>
                                </li>
                                <li class="x-menu-list-item x-menu-item-active">
                                    <a id="forward-object" class="x-menu-item" href="#" unselectable="on" hidefocus="true">
                                        <img id="ext-gen10" class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/shape_move_forwards.png">
                                        <span id="ext-gen11" class="x-menu-item-text">Bring Forward</span>
                                    </a>
                                </li>
                                <li class="x-menu-list-item x-menu-item-active">
                                    <a id="bringfront-object" class="x-menu-item" href="#" unselectable="on" hidefocus="true">
                                        <img id="ext-gen10" class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/shape_move_front.png">
                                        <span id="ext-gen11" class="x-menu-item-text">Bring to Front</span>
                                    </a>
                                </li>
                        </div>

                        <div class="rightClickPopup2">
                            <ul class="x-menu-list">

                                <li class="x-menu-list-item x-menu-item-active name-clip-menu">
                                    <a id="zoom-in" class="x-menu-item" href="#" unselectable="on" hidefocus="true">
                                        <img  class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/zoom_in.png">
                                        <span  class="x-menu-item-text">Zoom In</span>
                                    </a>
                                </li>
                                <li class="x-menu-list-item">
                                    <a id="zoom-out" class="x-menu-item disabled" href="#" unselectable="on" hidefocus="true">
                                        <img  class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/zoom_out.png">
                                        <span  class="x-menu-item-text">Zoom Out</span>
                                    </a>
                                </li>
                                <li id="x-menu-el-ext-comp-1003" class="x-menu-list-item x-menu-sep-li name-clip-menu">
                                    <span  class="x-menu-sep">&nbsp;</span>
                                </li>

                                <li class="x-menu-list-item name-clip-menu ">
                                    <a id="paste-object" class="x-menu-item disabled" href="#" unselectable="on" hidefocus="true">
                                        <img  class="x-menu-item-icon " src="<?php echo $webpath; ?>js/designer/assets/images/rightClickControlls/paste_plain.png">
                                        <span  class="x-menu-item-text">Paste</span>
                                    </a>
                                </li>


                            </ul>	
                        </div>

                        </section><!--tool-product-->
                    </div>




                    <footer>
                        <span>Airborne &copy; 2014 <a href="#">Magento Themes</a> Demo Store. All Rights Reserved. Designed by <a href="#">MagenTech.Com</a></span>
                    </footer>

                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/libraryjs/jquery.ui.touch-punch.min.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/libraryjs/fabric.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/services/colorbinding.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/services/popupmanager.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/services/customServices.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/changeviewcontroller.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/toolevent.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/addtextcontroller.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/addartcontroller.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/addnamecontroller.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/addnotecontroller.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/swapitemcontroller.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/swapitemdetailcontroller.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/addnamenumcontroller.js"></script>
                    <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/controllers/namenumberpage1controller.js"></script>
                    <div id="back-can" style="width: 100px;height: 100px;border:1px solid red;display:none;"></div>
                </div><!--designer-tool-->
                <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/libraryjs/bootstrap.js"></script>
                <script src="<?php echo $webpath; ?>../js/designer/libraryjs/jquery.form.js"></script>
                <script type="text/javascript" src="<?php echo $webpath; ?>../js/designer/libraryjs/file.js"></script>





                        </div>
                    </div>
                </div>
            </div>
        </div>
                                

    </div>
</div>
