<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/atlas/css/atlasbanner.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/base/default/trackorder/css/trackorder.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/base/default/css/magebuzz/testimonial/testimonial_slider.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/base/default/css/sparx/quicklogin/quicklogin.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/css/tm/easytabs.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/css/owl.carousel.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/css/owl.transitions.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/css/jquery.fancybox.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/css/helpers/jquery.fancybox-buttons.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/css/perfect-scrollbar.css" media="all" />
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/prototype/prototype.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/lib/ccard.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/prototype/validation.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/scriptaculous/builder.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/scriptaculous/effects.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/scriptaculous/dragdrop.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/scriptaculous/controls.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/scriptaculous/slider.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/varien/js.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/varien/form.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/mage/translate.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/mage/cookies.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/Atlas/jquery.min.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/Atlas/jquery.bxslider.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/Atlas/jquery.bxslider.min.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/magebuzz/testimonial/jquery/jquery.min.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/magebuzz/testimonial/jquery/jquery.bxslider.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/js/magebuzz/testimonial/jquery/testimonial_slider.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/lib/modernizr.custom.min.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/lib/selectivizr.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/lib/matchMedia.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/lib/matchMedia.addListener.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/lib/enquire.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/app.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/lib/jquery.cycle2.min.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/lib/jquery.cycle2.swipe.min.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/slideshow.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/lib/imagesloaded.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/minicart.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/base/default/js/tm/easytabs.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/jquery.BlackAndWhite.min.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/jquery.fancybox.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/helpers/jquery.fancybox-buttons.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/jquery.scrollpanel-0.5.0.js"></script>
<script type="text/javascript" src="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/js/custom.js"></script>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=PT+Sans:400,400italic,700,700italic" />
<!--[if  (lte IE 8) & (!IEMobile)]>
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/css/styles-ie8.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/css/madisonisland-ie8.css" media="all" />
<![endif]-->
<!--[if (gte IE 9) | (IEMobile)]><!-->
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/css/styles.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://dev.demosparx.in/NR339/skin/frontend/rwd/airborne/css/madisonisland.css" media="all" />
<!--<![endif]-->
<!-- Latest compiled and minified JavaScript -->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>-->

<script type="text/javascript">
//<![CDATA[
Mage.Cookies.path     = '/NR339';
Mage.Cookies.domain   = '.dev.demosparx.in';
//]]>
</script>
<meta name="viewport" content="initial-scale=1.0, width=device-width" />

<script type="text/javascript">
//<![CDATA[
optionalZipCountries = ["HK","IE","MO","PA"];
//]]>
</script>
<script type="text/javascript">//<![CDATA[
        var Translator = new Translate([]);
        //]]></script>
</head>
