var siteUrl=site_Url;
var dataAccessUrl=dataAccess_Url;
var loginType=login_Type;
var hoodieFlag=hoodie_Flag;
var editFlag=edit_Flag
var editDesignFlag=editFlag;
var dirPath=dir_Path;
var imgpath=imageHttpPath;
var getHelpUrl=get_Help_url;
var sleevPrintUrl=sleev_Print_url;
var sizePopup=dataAccess_Url+"sizechart";
var sleevePrint=sleeve_Print;
var swapPrint;
var locationUrl='';
var mobileMode=false;
var pdfScaleValue=2;
var undoredoVar=new Array();
var dataLessJson=new Array();
var editCanvasArr;
var pdfDrawAreaArr=new Array();
var designChangeFlag=false;
var hoodiesOrBlanket='';
var selectedBorderFlag=false;
var hoodisDesignData;
var blanketDesignData;
var blanketsBorderData;
var selectedBlanketThumb;
var detectArr=new Array();
var manageLayerCounter=0;
var selectedBlanketLayerId;
var blanketDesigner=blanket_designer;
//alert(editFlag)
var rotateCur=siteUrl+"assets/images/HImage/Rotate.cur";
var defaultFontSize = 20;
var currentSelectedTab=0;
var scaleRatioFlag=true;
var scaleRatioWidth=0;
var scaleRatioHeight=0;
var canvas;
var artResetInDeletePageFlag=false;
var nameFontTTF='';
var numberFontTTF='';
var adminDesignName='';
var frontCanvas;
var backCanvas;
var artResetValue=1;
var uploadCanvas;
var uploadThumb='';
var uploadColorArr=new Array();
var uploadedImageColorArr=new Array();
var viewLayerCount=0;
var viewLayerObj=new Array();
var img1=new Array();
var img2=new Array();
var selectedViewCanvas;
var rootApp;
var sharelink='';
var selectCat;
var selectCatArr=new Array();
var assignCategory='';
var notes='';
//alert(hoodieFlag)
var greekPopUpUrl=siteUrl+"assets/images/greekletter.jpg";
//alert(product_Id)
var selectedViewCanvas;
var maintainDrawAreaArr=new Array();
var selectedDrawAreaTitle='';
var preDeleteObj;
var tableRowCounter=0;
var productId=product_Id;
var designId=design_Id;
var selectedProductId;
var productColorId;
var mainSizesData;
var productColorValue;
var greekPopUpWindow;
var allCategory;
var pCatTitle;
var pSubcatTitle;
var canWidth=546;
var canHeight=493;
var layerWidth=0;
var layerHeight=0;
var layerX=0;
var layerY=0;
var resCanRatio=0;
var nameNumPersonalization='';
var clippingDrawArea=new Array();
var npx;
var npy;
var frontInkColorPrice=0;
var backInkColorPrice=0;
var selectedCatOrSubTitle;
var productsData;
var toolProductData;
var copyCutObject;
var currentView=0;
var subProductId=0;
var nameWidth=183;
var nameHeight=42;
var numberHeight=164;
var numberWidth=185;
var drawAreaGrpArr=new Array;
var drawAreaCounter=0;
var zoomInOutStr="zoomin"
var canvasScale = 1;
var SCALE_FACTOR=1.4;
var fontTTF;
var viewWiseScale=new Object();
var drawAreaGrp;
var productType="normal";
var selectedLayerColorData;
var selectedLayerEnabled=false;
var frontIndexObj=new Array();
var backIndexObj=new Array();
var selectedLayer="layer0";
var defaultLayerType='';

var clickEventType=((document.ontouchstart!==null)?'click':'touchstart');
//alert(clickEventType)
var colors;

var nameNumberQuantArr=new Array();
var nameNumberSendInfoArr=new Array();
var nameNumberQuantity=0;
var selectedNamePage="home";
var selectedColorName="White";
var global_SelectedItem;
var selectedSwapColorName='';
var rgb_value;
var nameSelectedColor="Black";
var nameColorLabel="Black";
var numberColorLabel="Black";
var nameBackColorHex="000000";
var nameAndNumberSelectedColor="000002";
var nameAndNumberFillColor="rgb(0,0,0)";
var numberBackColorHex="000000";
var nameHexColor="000002";
var resetNameNumberTableArr=new Array();
var nameNumRemoveFlag=true;
var numberHexColor="000002"
var nameFillColor="rgb(0,0,0)";
var numberFillColor="rgb(0,0,0)"
var nameSidePreIndex=1;
var nameSideNextIndex=1;
var numberSidePreIndex=1;
var numberSideNextIndex=1;
var stopPropagationFlag=true;
var colorPickerValue;
var nameCheck=false;
var nameColorPrice=0;
var numberColorPrice=0;
var numberCheck=false;
var nameView=1;
var numberView=1;
var selectedProductName;
var selectedColorThumbFlag=false;
//var jq=jQuery.noConflict();
var productDetailData;
var selectedQuantity=1;
var selectedSizes='XL-4S';
var customColorsArr=new Array();
var customSwapColorsArr=new Array();
var selectedCatId=0;
var swapcolors;
var nameColor;
var nameObj;
var numberObj;
var shapeType;
var shippingZipCode;
var sizeWiseQty;
var nameColorsArr=new Array();
var nameSizes;
var nameHeightSelectIndx=0;
var numberHeightSelectIndx=4;
var productSelectedName;
var productQtyLabel='';
var frontCanObjects=false;
var backCanObjects=false;
var canvasArr = new Array();
var dataArray = new Array();
var previewArr=new Array();
var viewWiseColorArr=new Array();
var outlineType="No Outline";
var outlineColorTitle='';
var textOutlineColorPrice=0;
var printPopup;
var textAndOutlineColorTitle='';
var textColorArr=new Array();
var textOutArr=new Array();
var textOutlineArr;
var outlineIndex=0;
var initFontData;
var textColorTitle='';
var textColorPrice='';
var textColor='';
var outlineWidth=0;
var textOutlineColor='';
var shapeSettingIndex=0;
var effectName='Normal'
var shapeSettingType='';
var shapeSelectIndx=0;
var archValue=0;
var arcRotate=0;
var roofGravity='';
var textAlign="center";

/***************text section data****************************/
var fontCategoryArr = new Array() ;
var fontDataArr;//new Array();
var selectedFontCategoryId;
var selectedFontCategoryIndex=0;
var selectedTtfPath;
var selectedArcValue=0;
var changeFontImageUrl;
var totalQty=0;
var totalPriceWithOutDisscount=0;
var totalPrice=0;
var singlePrice=20.75;
var discountPrice=13.24;
var shippingAddress='';
var priceData;
var discountPercentage=0;
var swapCategoryId;
var preX;
var preY;
var ORIGINAL_WIDTH;
var ORIGINAL_HEIGHT;
var saveDesignName='';
var saveEmailId='';
var userDesignId='';
var initArtData;
var clipartData;
var artCatSubTitle='';
var clipCatId;
var artSwitchValue=1;
var subCategoryArt;
var artLock=true;
var clipArtColors;
var artSelectedColorTitle='Black';
var artSelectedColorFill='rgb(0,0,0)';
var artSelectedColorCode='000000';
var artSelectedColorPrice='000000';
var artColorsArr=new Array();
var conert1Flag=false;
var clipColorable=0;
var clipUpload='clip';
var greekFontUrl='';
var greekFontTTF='';
var greekFlag=false;
var greekSelectedIndx=0;
var normalFontUrl='';
var normalFontTTTF='';
var normalFlag=false;
var normalSelectedIndx=0;
var uploadColorEdit=false;
var canPrint=parseInt(can_print);
var nameNumberFontsData='';
var nameFontSelectIndx=0;
var numberFontSelectIndx=0;
var nameFontTitle='';
var numberFontTitle='';

/***************end of text section data****************************/
//http://magento.thesparxitsolutions.com/magento/NR317/designersoftware/popup/category

var distressUrl=siteUrl+'assets/images/distress.png';
var distressOpacity=0;
var babyBlanketTitle='';
var topRightImage = new Image();

topRightImage.src = siteUrl+'assets/images/HImage/rotate.png';
var left_resize = new Image();
left_resize.src = siteUrl+"assets/images/HImage/index.png";
var right_resize = new Image();
right_resize.src = siteUrl+"assets/images/HImage/right-resize11.png";
var bottom_up_resize = new Image();
bottom_up_resize.src = siteUrl+"assets/images/HImage/botom-up-resize.png";
var left_right_resize = new Image();
left_right_resize.src = siteUrl+"assets/images/HImage/left-right.png";
var rotate = new Image();
rotate.src = siteUrl+"assets/images/HImage/rotate.png";
var bottmRightImage = new Image();
bottmRightImage.src = siteUrl+'assets/images/HImage/left-resize1.png';
var rotateCur=siteUrl+"assets/images/HImage/Rotate.cur"
angular.element(document).ready(function(){
	
	
});
